import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Hulu-clone by Zack Le</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hulu.ico" />
      </Head>

      <h1>let make this</h1>
    </div>
  )
}
